### ISSUE TITLE
Dependencie errors

### ISSUE THREAD

**Issue by Pintglass** [thaneb/TL-MR3020-OpenWRT-Extroot-Ready#3]
Hi
I am trying to install the package openvpn-openssl from your packages located at (73connection.com/openwrt/targets/ar71xx/tiny/packages/Packages.gz) but I'm getting dependencie errors, is there anything I can do about this?

Regards Pintglass

**Comment by thaneb** [comment]
Sorry for the delay, does the system tell you which dependency cannot be satisfied?

**Comment by thaneb** [comment]
I am now uploading a fresh build set (from 08.2020 sources), then I will update all feeds and sources and look if I can compile an updated build set.

**Comment by Pintglass** [comment]
Thanks but I did get it to install by using --force depends I know thats not the done thing but it seems fine apart from I can not get  a vpn setup but thats a different issue.

**Comment by Pintglass** [comment]
Is there any chance you could upload a sysupgrade image as there is not one present in your latest build

**Comment by thaneb** [comment]
I don't know what happen to the build process, sorry I'm quite busy now, so i deleted the last build which failed to create the sysupgrade and put back the last successful build and its packages. Could you please this time tell me what dependency error you have and what you are trying to achieve ?

**Comment by Pintglass** [comment]
Hi thanks for the reply, yes I am trying to install Kmod-tun which is needed for openvpn. In your builds when installed using the sysupgrade or factory image I have a vermagic of 93670ba717defa51fd997332fb8d8852 for the kernel where as your packages have c89bdd1d341546b374ef3d5dee8e2302 this is why Im getting the failed dependancy errors, like I said before I can do a --force-depends but then the module fails to load. This is with your builds dated 2020-08-07.

Regards Pintglass

**Comment by thaneb** [comment]
Hum, very strange, because with this build i was able to use the MR3020 as a vpn bridge (internet on the wifi or the ethernet port, and wifi or wire client going through the vpn link established by the mr3020).
So the mr3020 should be able to act as a client, but as server, I think it won't be possible due to its to limited memory.
Anyway, I am sorry to inform you that I will be able to work on this and try to solve the build issue only next week, I have the family to take care for few days.. sorry, I will look and update you ASAP. THanks.

**Comment by Pintglass** [comment]
Thats pretty much what I'm trying to do myself, to have the vpn as client so that wifi devices can use it. No rush family is far more important. All the best.
Pintglass

**Comment by thaneb** [comment]
Sorry for having been disconnected so long 😅 
As i finally got "my devices back" (by returning home) I just started a new rebuild, last time we spoke i had compilations errors and I moved before being able to sort that out.. 
the freshly compiled files are now synced and working, i will add new ipks step by step to avoid mixing not synced files between two build or build attempts 😅 I will try to add the more vpn related ipk asap, because i know it's the moste interesting activity field to play with a mr3020, but i already saw that it could lead to compilations issue when trying to compile with openssl support, so i cannot guarantee openwrt usual options will be all available 😅🙏🏻

**Comment by thaneb** [comment]
openvpn-openssl_2.4.11-1_mips_24kc.ipk added with luci openvpn ipk as well
but if you can you wrireguard instead, performances should be much more better
