### ISSUE TITLE
Can't install kmod-fs-exfat

### ISSUE THREAD

**Issue by will677667** [thaneb/TL-MR3020-OpenWRT-Extroot-Ready#4]
Hi
Tried to install exfat for mr3020 with your build of 19.07

opkg update
opkg install kmod-fs-exfat
Unknown package 'kmod-fs-exfat'.
Collected errors:
 * opkg_install_cmd: Cannot install package kmod-fs-exfat.
 
Is this possible to have it compiled because it looks like it's not present

Thanks in advance

**Comment by thaneb** [comment]
Hi Will, 
I got some issue with the VM I used to build this OpenWrt, but I found this package already build in another directory I created while playing to build last year, so I uploaded this package, can you try to refresh and install it again?

**Comment by will677667** [comment]
Hi thaneb,

Thank you but it doesn't install.

It asks kernel 4.14.180-1-6dec97b477ceaa50e04993e10826601e
where as your build of 19.07 for mr3020 has kernel 4.14.180-1-c89bdd1d341546b374ef3d5dee8e2302
I saw you have added several kmods ipk like vfat, fuse. I tested them but the problem is still the same.

**Comment by thaneb** [comment]
OK ok, then I will have to look to get a new successful compilation, hope being able to find that tomorrow

**Comment by will677667** [comment]
Ok Thank you very much

**Comment by keecy** [comment]
Hi everybody, 

I have the same problem here.

By the way when i update lists in luci i get

Downloading http://73connection.com/openwrt/targets/ar71xx/tiny/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_core
Downloading http://73connection.com/openwrt/targets/ar71xx/tiny/packages/Packages.sig
Signature check failed.
Remove wrong Signature file.

Let me know if you overcome this. or find other solution.

Thanks for the effort and the contibution.

Br, 
keecy

**Comment by will677667** [comment]
Hi
I have found another solution to the problem.
you can go to https://eko.one.pl/ they have complete openwrt extroot 19.07 firmware for MR3020

**Comment by keecy** [comment]
Hi, 
Thanks for the fast reply!
I will try it :)

**Comment by thaneb** [comment]
Hope you find what you needed with this interesting source 🙏🏻
I just got the time and ressources to set up a new build environment and started a fresh new build..
I will try to compile more ipk every day, and refresh all the uploaded files every times something is added. I tried toake a full build, but i ran into compilations errors, and I guess it's better to add ipks step by step in order to avoid the mess of incompatible signature and not synced packages with the firmware..
I close this request as the new build set is working well and is sync with all available package in the repo.
Sorry again for not being able to come back to this project earlier (covid prevented me to come back home for about 2 years 😅 cannot complain because I stayed at the beach, but I've been "disconnected" 😅)
