### ISSUE TITLE
sysupgrade and kmod version mistmatch for TL-MR3020

### ISSUE THREAD

**Issue by alexsorinpop** [thaneb/TL-MR3020-OpenWRT-Extroot-Ready#5]
Hi

   The kernel version in the sysupgrade file (http://www.73connection.com/openwrt/targets/ar71xx/tiny/openwrt-19.07-ar71xx-tiny-tl-mr3020-v1-squashfs-sysupgrade.bin) is @ version 4.14.180-1-96370ba717defa51fd997332fb8d8852 while the version of the kmod in http://www.73connection.com/openwrt/targets/ar71xx/tiny/packages/ is @ version 4.14.180-1-c89bdd1d341546b374ef3d5dee8e2302

   Can you please provide a sysupgrade file for 4.14.180-1-c89bdd1d341546b374ef3d5dee8e2302 or add the old kmod modules to some path? Or maybe rebuild everything so the kernel and the mods are at the same version!?!

Thanks

**Comment by thaneb** [comment]
Thanks for your request and really sorry to answer so late 🙏🏻, covid disconnected me from my life and usual ressources and I just finally got the time and ressources to set up a new build environment and started a fresh new build..
I will try to compile more ipk every day, and refresh all the uploaded files every times something is added. I tried toake a full build, but i ran into compilations errors, and I guess it's better to add ipks step by step in order to avoid the mess of incompatible signature and not synced packages with the firmware..
I close this request as the new build set is working well and is sync with all available package in the repo.
Sorry again for not being able to come back to this project earlier (covid prevented me to come back home for about 2 years 😅 cannot complain because I stayed at the beach, but I've been "disconnected" 😅)
