### ISSUE TITLE
Use official repo

### ISSUE THREAD

**Issue by HuJK** [thaneb/TL-MR3020-OpenWRT-Extroot-Ready#7]
Hi, is it safe to use [official repository](http://archive.openwrt.org/releases/19.07.10/targets/ar71xx/tiny/packages) instead of yours like this?
![image](https://user-images.githubusercontent.com/15907444/229708345-29c6ef88-b2e9-4648-85eb-537c430042d0.png)

I want to install kmod-gre which is not included in your repository, I'm not sure it is safe to install official repository directly.
![image](https://user-images.githubusercontent.com/15907444/229708661-3ae99cb0-59ac-40c8-bd3f-cb72b64b14f5.png)

**Comment by thaneb** [comment]
Hello and thank you for your message, i won't have any access to my builder until May the 10th, so I'm sorry to say that you will need to wait to know if the build is doable or not with kmod-gre as option (it's possible that it broke the build). I will update you ASAP concerning this question.
On the other side, i would say you can always try to use the official openwrt repo, 3 things may happen:
1- opkg successfully install and it's good
2- opkg refuse to install because of incompatibility or dependency issue
3- you force opkg to install, it may work or broke the system, and if it broke it, you will need to reset and reconfigure your router. Note that, if you are using the extroot, you only need to boot without the usb key plugged to "slightly reset" the system (it will bring you back at the step "plug the usb, use the script to format usb and configure the extroot)

**Comment by thaneb** [comment]
New build complete with kmod-gre compiled as kernel module. uploading files now, should be all online in 4 minutes.

**Comment by thaneb** [comment]
upload complete, please confirm if what you trying to do is working or if you need more compilation :)
